histovec/histovec-beta

infrastructure/heat-templates/CIT/back_postconf.sh, infrastructure/heat-templates/CIT/bastion_postconf.sh, infrastructure/heat-templates/CIT/front_postconf.sh, infrastructure/heat-templates/CIT/histovec-parameters.yaml, infrastructure/heat-templates/CIT/histovec.yml, infrastructure/heat-templates/floating-ip/heat-parameters.yaml, infrastructure/heat-templates/floating-ip/heat.yaml
mise en place de l'infra as code pour le développement.
les paramètres sont à modifier pour prendre en compte l'environnement cible.
=> init infra as code

.gitignore, infrastructure/heat-templates/CIT/back_postconf.sh, infrastructure/heat-templates/CIT/bastion_postconf.sh, infrastructure/heat-templates/CIT/front_postconf.sh, infrastructure/heat-templates/floating-ip/heat.yaml
finalisation des templates d'infrastructure et externalisation des paramètres stockés dans un dépôt privé.
=> template infra

frontend/src/components/Report.vue, frontend/static/assets/css/style.css
** Report **
- spinner when loading request
- full width (working only in firefox)
=> Small fixes

Makefile, nginx/nginx-dev.template
updated dev conf, migrating uri from / to /histovec
=> Dev : moved to /histovec

Makefile, docker-compose-run-frontend.yml, frontend/package.json, frontend/src/components/Report.vue, nginx/nginx-dev.template, nginx/nginx-run.template
- hide elasticsearch calls from front
- rewrite and check call validity from nginx
- filter the data from nginx
=> Secured api calls

frontend/src/components/Faq.vue, frontend/src/components/Legal.vue
=> Maj texte FAQ Legal

Makefile, frontend/src/components/Report.vue
=> Date du dernier certificat

frontend/src/components/Report.vue, frontend/src/components/Search.vue
=> Search / Report : masquer les données identifiantes de l'URL pour le vendeur

frontend/src/components/Report.vue
=> Report: padding code postal

frontend/src/components/Home.vue, frontend/src/components/Search.vue
=> Search: switch query to params for persona type

frontend/src/components/Contact.vue, frontend/src/components/Faq.vue, frontend/src/components/Feedback.vue, frontend/src/components/Legal.vue, frontend/src/components/Report.vue, frontend/src/components/Search.vue
- holder messages
- occasSion fix !
=> Minor fixes

frontend/package.json, frontend/src/components/Report.vue
Blocks report rendering if whole report not fullfilled
=> Bug fix #202

frontend/src/App.vue, frontend/src/assets/json/verbatims.json, frontend/src/assets/scss/_style.scss, frontend/src/assets/scss/style.scss, frontend/src/components/Home.vue
=> Home: added verbatims

nginx/nginx.conf
=> ajout IP source dans les log nginx

frontend/src/App.vue, frontend/src/components/Faq.vue, frontend/src/components/Home.vue, frontend/src/components/Legal.vue, frontend/src/components/Report.vue, frontend/src/components/Search.vue, frontend/src/main.js, frontend/src/router/index.js
Ajout alt et description + formulaire (indication obligatoire) et navigation clavier
=> Correction a11y

frontend/src/components/Report.vue
=> Report: précaution sur le calcul des titulaires cas FNI et immat étranger

frontend/src/components/Legal.vue
Je propose ce chapitre en reprenant notamment des éléments du doc de fabien pour le rssi
merci de relire @philippeBron @rhanka 
est-ce qu'il faut ajouter un point sur la purge de données. Je ne sais pas quoi mettre là dessus, vu qu'on dit qu'il n'y a pas de stockage de données perso, qu'est-ce qu'on a a purger ?
=> ajout du chapitre Protection des données

frontend/src/components/Search.vue
champs dateNaissance et plaque
=> ajout controle formulaire

frontend/src/components/Buyer.vue
ajout du bouton d'envoi de mail sur la page acheteur pour demander le rapport histovec au vendeur
=> bouton demande de rapport

frontend/src/components/Buyer.vue
Fix build frontend: remplacement des simple quote dans var text.
=> Fix: echappement des simple quotes dans les var text

frontend/src/components/Report.vue
Impossible de soumettre a cause du bouton envoyer
=> Bug formulaire eval 

.gitignore, .travis.yml, Makefile, Makefile.deploy, README.deploy.md, README.md, README.travis.md, docker-compose-build-deploy-frontend.yml, docker-compose-build-frontend.yml, docker-compose-run-nginx-frontend.yml, frontend/Dockerfile.build-deploy, nginx/Dockerfile.build, nginx/run.sh, tests/test-up-elasticsearch.sh, tests/test-up-histovec.sh, tests/test-up-nginx.sh
* Ajout du build via travis-ci.org:
* Ajout du fichier de build .travis.yml
* Ajout du README.travis.md pour la effectuer la configuration initiale github/travis
* Ajout du resultat du build sous forme d'image (travis status) dans le README principal
* Makefile: suppression des espaces de fin de lignes inutiles et correction tabspace
* correction variable APP_VERSION  et image:APP_VERSION
* Ajout du Makefile.deploy , pour le build/deploiement dans les environnements
=> Ajout build travis

.gitignore, .travis.yml, Makefile, Makefile.deploy, tests/test-up-elasticsearch.sh, tests/test-up-histovec.sh, tests/test-up-nginx.sh
* build images
- make -f Makefile.deploy build-all-images
* up
- make -f Makefile.deploy up-all
* create test env
- make -f Makefile.deploy wait-elasticsearch
- make -f Makefile.deploy index-create
- make -f Makefile.deploy index-status
* test env
- make -f Makefile.deploy test-up
* teardown
- make -f Makefile.deploy down-all
=> Travis: Ajout tests de deploiement (up and running): elasticsearch, nginx, appli

frontend/src/components/Buyer.vue, frontend/src/components/Contact.vue, frontend/src/components/Faq.vue, frontend/src/components/Feedback.vue, frontend/src/components/Home.vue, frontend/src/components/Legal.vue, frontend/src/components/NotFound.vue, frontend/src/components/Report.vue, frontend/src/components/Search.vue, frontend/src/main.js, nginx/nginx-dev.template, nginx/nginx-run.template, nginx/nginx.conf
Logs every major page change and catches exit, for analytics.
Further analytics could now be implementend using heatmaps.js
=> log api #322

frontend/src/components/Report.vue, frontend/src/components/Search.vue
#353 
+ bouton de renvoi vers la FAQ
=> Esthétique et numero d'appel PV

frontend/src/components/Buyer.vue
Allègement du message pour plus de convivialité
=> Modification du message mail du vendeur à l'acheteur

frontend/src/components/Report.vue
dans le cas où INSCRIRE_OVE et DEC_VE sont présents
=> #200 correction nombre de sinistres 

frontend/src/components/Faq.vue
=> 'FAQ': Rajout d'un glossaire des termes Historiques

frontend/src/components/Faq.vue
FAQ : Changer l’entête “terminologie d..” sous forme de question : “que signifie les termes des opérations…”
=> FAQ Changement de formulation  #371

frontend/src/components/Buyer.vue, frontend/src/components/Report.vue
ajout lien vars site vignette crit'air issue #380 
ajout formule page buyer fonctionnement du mailto #351
=> Correctifs lien crit'air & alerte mailto

frontend/src/components/Report.vue
with ctrl+alt+a & ctrl+alt+p : all sections pdf print
=> hidden functionnalities 

frontend/src/components/Report.vue
en attente d'activation, la date se mettra automatiquement à jour, pour l'instant accessible en appuyant sur ctrl+alt+m
=> date update from data #381

.travis.yml
=> fix travis build: https://github.com/travis-ci/travis-ci/issues/7422

Makefile, docker-compose-run-frontend.yml, frontend/src/components/Report.vue, nginx/Dockerfile.build, nginx/nginx-dev.template, nginx/nginx-run.template, nginx/nginx.template
Afin de faciliter la gestion inter environnements (test, dev, prod), la régulation est paramétrisée : 
- zone (par défaut http_x_forwarded_for, surcharchable à binary_remote_addr)
- limite de l'API par user : une requête par minute
- burst de l'API par user : droit à 5 requêtes sans délai
- limite de l'API au global : 5 par seconde, avec un pic à 20 sans délai
=> Nginx: regulation paramétrable et augmentée par défaut

docker-compose-run-nginx-frontend.yml, nginx/run.sh, tests/fake-curl.sh, tests/test-up-elasticsearch.sh, tests/test-up-nginx.sh
Nginx: fix parametres au run time
=> Nginx: fix parametre au run time

frontend/src/assets/json/libelle_operations.json, frontend/src/components/Report.vue
ayant "IMMAT_NORMALE_PREM_VO"  comme première opération
=> bug véhicules non importé #406

tests/test-up-elasticsearch.sh
=> Fix test elastic: nb indice >=3

frontend/src/components/Faq.vue
Suppression des balises <B> par <span class="bold_6">
Ajout Explication premiere immatriculation source inconnue
=> FAQ Explication premiere immatriculation source inconnue #419

nginx/nginx.template, nginx/run.sh
Add nginx log json with following format:
* to activate in prod, must comment/uncomment access_log section
```
{ "nginx": {
"http_x_forwarded_for":"$http_x_forwarded_for",
"http_referer":"$http_referer",
"http_user_agent":"$http_user_agent",
"remote_addr":"$remote_addr",
"remote_user":"$remote_user",
"time_local":"$time_local",
"request":"$request",
"request_time":$request_time,
"request_method":"$request_method",
"request_uri":"$request_uri",
"uri":"$uri",
"status":$status,
"body_bytes_sent":$body_bytes_sent,
"upstream_addr":"$upstream_addr",
"upstream_status":"$upstream_status",
"upstream_response_time":$upstream_response_time_val,
"pipe":"$pipe"
}
}
```
=> Add nginx log json

frontend/src/components/infos/Faq.vue
=> Fix bug on second item in FAQ

client/Dockerfile, docker-compose-run-client.yml
fix ssh+git error 
* configure git to use https:// instead of git://
* (optional): use internal debian mirror if needed
=> Tech/use vue cli 3 dockerize - fix ssh+git error

frontend/build/dev-client.js, frontend/build/dev-server.js, frontend/build/webpack.dev.conf.js, nginx/nginx-dev.template
=> tech: fix hot-reload

frontend/src/components/infos/Legal.vue, frontend/src/components/infos/faq-content.js
#570 FAQ suppression d'une ligne en double
#573 Mentions Légales correction et ajout à la demande de la DSR
=> #570 #573 correction et ajout 

Makefile, Makefile.deploy
Add Makefile target download-all-images load-all-images
=> Add Makefile target download-all-images load-all-images

Makefile, Makefile.deploy
=> :recycle: reorder load and download make targets

frontend/src/App.vue, frontend/src/constants/mail.js, frontend/src/utils/mail.js
=> add mail util and update contact/error mail content

frontend/src/components/Report.vue, frontend/src/components/reportParts/Abstract.vue, frontend/src/components/reportParts/Administrative.vue, frontend/src/components/reportParts/AdministrativeCertificate.vue, frontend/src/components/reportParts/History.vue, frontend/src/components/reportParts/License.vue, frontend/src/components/reportParts/Share.vue, frontend/src/components/reportParts/TechChars.vue, frontend/src/components/reportParts/TechControl.vue, frontend/src/components/reportParts/TechControlGraph.vue
=> add log when changing report tab

frontend/src/components/infos/faq-content.js
=> :pencil2: Fix FAQ (closes #746)

Makefile, backend/.gitignore, backend/redis/Dockerfile, backend/redis/redis.conf, docker-compose-backend.yml, docker-compose-dev-backend.yml
=> redis redis.conf Dockerfile with configuration for deployment

Makefile, docker-compose-backend.yml, docker-compose-dev-backend.yml, docker-compose-elasticsearch.yml
redis data directory must be present before starting. 
redis is launched in container as user redis (uid: 100, gid: 100)
=> redis data directory must be present before starting

Makefile, dataprep/crypt.py, frontend/src/components/Search.vue, frontend/src/store/index.js
fix #768 - suppression idv dans elasticsearch
fix #683 - changement des secrets
fix #767 - copier coller compatible avec dates de naissances
=> Big bang/secrets

frontend/src/store/modules/utac.js
=> hash key before sending it to backend, for increased security

frontend/src/router/index.js, frontend/vue.config.js
=> link to Faq, Legal, Buyer

Makefile, docker-compose-build-frontend.yml, frontend/Dockerfile, frontend/vue.config.js
=> source map parametrize and reactivate by default

Makefile
=> switch to official mail

backend/src/app.js, nginx/nginx-run-v1.template
=> :sparkles: backend - add forwarded ip to log

frontend/src/App.vue, frontend/src/components/Report.vue, frontend/src/components/infos/Faq.vue, frontend/src/components/infos/faq-content.js, frontend/src/store/index.js
1. UTAC conf depends on V1 conf
2. modalMail conf depends on V1 conf
3. Default UTAC conf to false - Closes #844
=> Fix utac and modalMail conf

Makefile
=> add aws ip blocking prerequisite as needed now in dev mode

backend/Dockerfile, frontend/Dockerfile
To use then new internal npm repo with autosigned cert, , disable ssl cert in npm
=> To use then new interna npm repo, disable ssl cert in npm

backend/src/config.js, backend/src/services/utac.js
In production, https is managed by the PIO.
=> :sparkles: use http for prod environment

.gitignore, Makefile, backend/package-lock.json, backend/src/routes/report.js, backend/src/services/utac.js, frontend/package-lock.json, frontend/src/api/index.js, frontend/src/components/Report.vue, frontend/src/components/Search.vue, frontend/src/components/reportParts/TechControl.vue, frontend/src/components/reportParts/TechControlGraphError.vue, frontend/src/store/modules/utac.js
- Fix BACKEND_SECRET for cache consistency purpose
- Enhance UTAC errors
- Fix FNI copy / past shortcut
- Manage UTAC tabs depending errors
- Ignore CSV cache files
=> Enhance UTAC and add some fixes

Makefile
=> :wrench: fix IS_UTAC_API_ACTIVATED to true since frontend is not

Makefile
Split SIV and IVT/FNI data injection
=> split siv and ivt injection

frontend/src/assets/js/siv.js, frontend/src/views/ContactPage.vue, frontend/src/views/RapportPage.vue
=> feat(): suppression des console.log restant

frontend/src/components/HistoVecFooter.vue
=> feat(): modification du footer pour respecter le dsfr

frontend/src/views/AcheteurPage.vue, frontend/src/views/FAQPage.vue, frontend/src/views/ProprietairePage.vue, frontend/src/views/RapportPage.vue
=> fix(): rendre les images de presentation responsive

frontend/src/views/FAQPage.vue
=> fix(): integrer les liens utiles dans des tuiles non cliquable sur la page FAQ

frontend/src/components/HistoVecModale.vue, frontend/src/main.js, frontend/src/views/RapportPage.vue
Correction de la fonction de copie du code et du lien de partage.
(032)
=> fix(): correction de la copie du code et du lien de partage

backend/src/plugins/public-api/util/mapping.js, backend/src/plugins/public-api/util/normalizeData.js
=> fix(): suppression des références non utilisées du mapping

backend/src/plugins/public-api/util/mapping.js, frontend/src/utils/mapping/index.js, frontend/src/views/RapportPage.vue
=> fix(): Suppression du numAgree

frontend/src/views/FAQPage.vue
=> fix():  renommer carte grise en certificat d'immatriculation sur la page FAQ

frontend/src/components/AlerteComponent.vue, frontend/src/views/RapportPage.vue
=> feat(): Ajout d'un alerte à la copie du lien de partage

frontend/src/assets/js/siv.js, frontend/src/views/RapportPage.vue
item 089
Onglet synthese : afficher les sinistres si existant dans la colonne situation administrative 
Onglet situation administrative : colonne suspensions, effectuer un retour a la ligne si plusieurs suspensions
=> fix(): Afficher la situation administrative pour un véhicule avec au moins 1 sinistre

frontend/src/views/RapportPage.vue
=> fix(): Conditionner l'affichage des liens d'information pour les véhicules de collection et/ou agricoles

frontend/src/views/FAQPage.vue
+ correction coquille sur intitulé accordéon
=> fix(RGAA-7.4): Permettre à la synthèse vocale de lire les accordéons 

frontend/src/views/RapportPage.vue
Erreur corrigé:
- Error: The aria-controls attribute must point to an element in the same document.
- Error: The aria-labelledby attribute must point to an element in the same document.
=> fix(RGAA-8.2): validator w3c sur RapportPage

frontend/src/views/ProprietairePage.vue
A l'appui du bouton Effacer, le formulaire est vidé et reste actif et le focus se fait au niveau de la plaque précédemment sélectionnée
=> fix(RGAA-11.9-12.8-7.4): Bouton Effacer réinitialise les champs du formulaire

frontend/src/views/ContactPage.vue
Erreur du validator w3c : 
- The aria-describedby attribute must point to an element in the same document. 
- Bad value CERTIFICAT_IMMATRICULATION for attribute type on element [button](https://html.spec.whatwg.org/multipage/#the-button-element).
=> fix(RGAA-8.2): validator sur ContactPage

frontend/src/views/ProprietairePage.vue
Erreur corrigée: 
- Error: The aria-labelledby attribute must point to an element in the same document.
- Error: The aria-controls attribute must point to an element in the same document.
- Error: Element [div](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [label](https://html.spec.whatwg.org/multipage/#the-label-element) in this context. (Suppressing further errors from this subtree.)
=> fix(RGAA-8.2): validator w3c sur ProprietairePage

frontend/src/constants/csaAsPdf.js, frontend/src/utils/csaAsPdf/content.js, frontend/src/utils/csaAsPdf/footer.js, frontend/src/utils/csaAsPdf/index.js, frontend/src/utils/csaAsPdf/utils.js, frontend/src/views/RapportPage.vue
=> refacto des constantes du csaPdf

backend/src/connectors/redis.js, backend/src/connectors/send-mail.js, backend/src/handlers/feedback.js, backend/src/index.js, backend/src/plugins/public-api/handlers/report.js, backend/src/plugins/public-api/routes/reportCommon.js, backend/src/plugins/public-api/util/check/reportByData.js, backend/src/routes/report.js, backend/src/server.js, backend/src/services/siv.js, backend/src/services/utac.js
Objectif de cette mr :
- simplifier l'écriture des logs avec des clés à la place des phrases
- retirer les information en doublons
- retirer les  icones
=> feat: simplification de l'affichage des logs
